const GENRE_LABELS = {
  action: "أكشن",
  adventure: "مغامرة",
  fantasy: "فانتازيا",
  "sci-fi": "خيال علمي",
  romance: "رومانسي",
  "slice-of-life": "شريحة حياة",
  sports: "رياضة",
  horror: "رعب",
  thriller: "إثارة",
  mystery: "غموض",
  mecha: "ميكا",
  music: "موسيقى",
  comedy: "كوميدي",
  drama: "دراما",
  historical: "تاريخي",
  supernatural: "خارق",
  isekai: "إيسيكاي"
};

const TYPE_LABELS = {
  TV: "مسلسل",
  Movie: "فيلم",
  OVA: "OVA",
  ONA: "ONA",
  Special: "خاصة"
};

const STATUS_LABELS = {
  Ongoing: "مستمر",
  Completed: "مكتمل",
  Hiatus: "متوقف"
};

const ERA_LABELS = {
  classic: "كلاسيكي",
  "2000s": "الألفينات",
  "2010s": "2010s",
  "2020s": "حديث"
};

const AR_TITLES = {
  naruto: "ناروتو",
  "one-piece": "ون بيس",
  "attack-on-titan": "هجوم العمالقة",
  "demon-slayer": "قاتل الشياطين",
  "jujutsu-kaisen": "جوجوتسو كايسن",
  "my-hero-academia": "أكاديمية بطلي",
  "fullmetal-brotherhood": "الكيميائي المعدني الكامل: الإخوة",
  "death-note": "ديث نوت",
  "steins-gate": "شتاينز غيت",
  "spy-family": "سباي × فاميلي",
  haikyuu: "هايكيو",
  "your-lie-in-april": "كذبتك في أبريل",
  "violet-evergarden": "فيوليت إيفرغاردن",
  "kaguya-sama": "كاغويا ساما: الحب هو الحرب",
  toradora: "تورادورا",
  "mushoku-tensei": "موشوكو تينسي",
  "re-zero": "ري:زيرو",
  "promised-neverland": "نيفَرْلاند الموعودة",
  "made-in-abyss": "ميد إن أبيس",
  "dr-stone": "دكتور ستون",
  "oshi-no-ko": "أوشي نو كو",
  frieren: "فرييرن: ما بعد نهاية الرحلة",
  "blue-lock": "بلو لوك",
  "chainsaw-man": "تشينسو مان",
  "vinland-saga": "ملحمة فينلاند",
  "mob-psycho": "موب سايكو 100",
  bocchi: "بوتشي ذا روك",
  parasyte: "باراسايت",
  "cowboy-bebop": "كاوبوي بيبوب",
  evangelion: "إيفانجيليون",
  "detective-conan": "المحقق كونان"
};

const OFFICIAL_PLATFORMS = [
  {
    id: "crunchyroll",
    label: "Crunchyroll",
    url: (title) => `https://www.crunchyroll.com/search?q=${encodeURIComponent(title)}`
  },
  {
    id: "netflix",
    label: "Netflix",
    url: (title) => `https://www.netflix.com/search?q=${encodeURIComponent(title)}`
  },
  {
    id: "hidive",
    label: "HIDIVE",
    url: (title) => `https://www.hidive.com/search?q=${encodeURIComponent(title)}`
  },
  {
    id: "hulu",
    label: "Hulu",
    url: (title) => `https://www.hulu.com/search?q=${encodeURIComponent(title)}`
  },
  {
    id: "prime",
    label: "Prime Video",
    url: (title) =>
      `https://www.primevideo.com/search/ref=atv_nb_sr?phrase=${encodeURIComponent(title)}`
  }
];

const getTrailerThumb = (id) => `https://i.ytimg.com/vi/${id}/hqdefault.jpg`;

const ANIME_DATA = [
  {
    id: "naruto",
    title: "Naruto",
    jp: "ナルト",
    tagline: "إرادة لا تنكسر وسط معارك النينجا.",
    description: "رحلة طويلة مليئة بالتحديات، الصداقة، والإصرار على تحقيق الحلم.",
    genres: ["action", "adventure", "supernatural"],
    type: "TV",
    status: "Completed",
    era: "2000s",
    score: 8.3,
    episodes: "طويل",
    duration: "23د",
    poster: "images (1).jpeg",
    palette: ["#f6c453", "#ff7b54"],
    tags: ["نينجا", "شونين", "قتال"]
  },
  {
    id: "one-piece",
    title: "One Piece",
    jp: "ワンピース",
    tagline: "مغامرة بحرية للعثور على الكنز الأسطوري.",
    description: "طاقم قبعة القش في رحلة مليئة بالمفاجآت، الجزر، والأحلام الكبيرة.",
    genres: ["action", "adventure", "fantasy"],
    type: "TV",
    status: "Ongoing",
    era: "2000s",
    score: 9.1,
    episodes: "طويل",
    duration: "24د",
    palette: ["#ffdd59", "#ff9f1a"],
    tags: ["قراصنة", "مغامرة", "طاقم"]
  },
  {
    id: "attack-on-titan",
    title: "Attack on Titan",
    jp: "進撃の巨人",
    tagline: "البشر ضد العمالقة في عالم قاسٍ.",
    description: "صراع ملحمي للبقاء مع أسرار تتكشف تدريجياً.",
    genres: ["action", "drama", "mystery"],
    type: "TV",
    status: "Completed",
    era: "2010s",
    score: 9.0,
    episodes: "متوسط",
    duration: "24د",
    palette: ["#64748b", "#1f2937"],
    tags: ["عمالقة", "حرب", "تشويق"]
  },
  {
    id: "demon-slayer",
    title: "Demon Slayer",
    jp: "鬼滅の刃",
    tagline: "سيوف، شياطين، وقلب لا ينهزم.",
    description: "رحلة مؤثرة لإنقاذ العائلة وسط معارك مذهلة بصرياً.",
    genres: ["action", "historical", "supernatural"],
    type: "TV",
    status: "Ongoing",
    era: "2010s",
    score: 8.7,
    episodes: "متوسط",
    duration: "24د",
    palette: ["#fca5a5", "#ef4444"],
    tags: ["شياطين", "سيوف", "عائلة"]
  },
  {
    id: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    jp: "呪術廻戦",
    tagline: "لعنات قوية ومعارك مرعبة.",
    description: "أبطال يواجهون مخلوقات مظلمة في عالم السحر الحديث.",
    genres: ["action", "supernatural"],
    type: "TV",
    status: "Ongoing",
    era: "2020s",
    score: 8.8,
    episodes: "متوسط",
    duration: "24د",
    palette: ["#60a5fa", "#1e40af"],
    tags: ["لعنات", "سحر", "قتال"]
  },
  {
    id: "my-hero-academia",
    title: "My Hero Academia",
    jp: "僕のヒーローアカデミア",
    tagline: "بطولة تتشكل من الصفر.",
    description: "طلاب بأحلام كبيرة في أكاديمية الأبطال.",
    genres: ["action", "fantasy", "comedy"],
    type: "TV",
    status: "Ongoing",
    era: "2010s",
    score: 8.1,
    episodes: "متوسط",
    duration: "24د",
    poster: "Season_1_Key_Visual_2.webp",
    palette: ["#38bdf8", "#0f172a"],
    tags: ["أبطال", "مدرسة", "شونين"]
  },
  {
    id: "fullmetal-brotherhood",
    title: "Fullmetal Alchemist: Brotherhood",
    jp: "鋼の錬金術師",
    tagline: "قصة أخوة في عالم الخيمياء.",
    description: "رحلة بحث عن الحقيقة بثمن باهظ ومشاعر قوية.",
    genres: ["action", "fantasy", "adventure"],
    type: "TV",
    status: "Completed",
    era: "2000s",
    score: 9.2,
    episodes: "متوسط",
    duration: "24د",
    palette: ["#f97316", "#7c2d12"],
    tags: ["خيمياء", "أخوة", "رحلة"]
  },
  {
    id: "death-note",
    title: "Death Note",
    jp: "デスノート",
    tagline: "معركة عقلية بين العبقرية والعدالة.",
    description: "دفتر غامض يقلب موازين العالم ويشعل صراعاً نفسياً حاداً.",
    genres: ["thriller", "mystery", "supernatural"],
    type: "TV",
    status: "Completed",
    era: "2000s",
    score: 8.9,
    episodes: "متوسط",
    duration: "23د",
    palette: ["#9ca3af", "#111827"],
    tags: ["ذكاء", "محقق", "توتر"]
  },
  {
    id: "steins-gate",
    title: "Steins;Gate",
    jp: "シュタインズ・ゲート",
    tagline: "تجربة زمنية بمخاطر لا تحصى.",
    description: "مجموعة أصدقاء يعبثون بالزمن في قصة عاطفية ومعقدة.",
    genres: ["sci-fi", "thriller", "drama"],
    type: "TV",
    status: "Completed",
    era: "2010s",
    score: 9.1,
    episodes: "متوسط",
    duration: "24د",
    palette: ["#c084fc", "#4c1d95"],
    tags: ["زمن", "تقنية", "تشويق"]
  },
  {
    id: "spy-family",
    title: "Spy x Family",
    jp: "SPY×FAMILY",
    tagline: "عائلة مزيفة بأسرار حقيقية.",
    description: "مزيج ممتع من الأكشن والكوميديا واللحظات الدافئة.",
    genres: ["comedy", "action", "slice-of-life"],
    type: "TV",
    status: "Ongoing",
    era: "2020s",
    score: 8.5,
    episodes: "قصير",
    duration: "24د",
    palette: ["#fde68a", "#f59e0b"],
    tags: ["جواسيس", "عائلة", "كوميديا"]
  },
  {
    id: "haikyuu",
    title: "Haikyuu!!",
    jp: "ハイキュー!!",
    tagline: "روح الفريق في أعلى مستوياتها.",
    description: "حماس كرة الطائرة مع تطور شخصيات ممتع للغاية.",
    genres: ["sports", "comedy", "drama"],
    type: "TV",
    status: "Completed",
    era: "2010s",
    score: 8.7,
    episodes: "متوسط",
    duration: "24د",
    palette: ["#fb923c", "#1d4ed8"],
    tags: ["كرة طائرة", "روح الفريق", "منافسة"]
  },
  {
    id: "your-lie-in-april",
    title: "Your Lie in April",
    jp: "四月は君の嘘",
    tagline: "الموسيقى تعيد الحياة من جديد.",
    description: "قصة رومانسية مؤثرة تدور حول الموسيقى والشفاء.",
    genres: ["romance", "drama", "music"],
    type: "TV",
    status: "Completed",
    era: "2010s",
    score: 8.6,
    episodes: "قصير",
    duration: "23د",
    palette: ["#f9a8d4", "#ec4899"],
    tags: ["بيانو", "مشاعر", "دموع"]
  },
  {
    id: "violet-evergarden",
    title: "Violet Evergarden",
    jp: "ヴァイオレット・エヴァーガーデン",
    tagline: "رسائل مكتوبة بالدمع.",
    description: "قصة شاعرية عن فهم المشاعر وتعلم الحب.",
    genres: ["drama", "slice-of-life"],
    type: "TV",
    status: "Completed",
    era: "2010s",
    score: 8.7,
    episodes: "قصير",
    duration: "24د",
    palette: ["#93c5fd", "#2563eb"],
    tags: ["رسائل", "مشاعر", "هدوء"]
  },
  {
    id: "kaguya-sama",
    title: "Kaguya-sama: Love is War",
    jp: "かぐや様は告らせたい",
    tagline: "حرب باردة بين قلبين.",
    description: "كوميديا رومانسية مع معارك نفسية لطيفة.",
    genres: ["romance", "comedy"],
    type: "TV",
    status: "Completed",
    era: "2010s",
    score: 8.4,
    episodes: "قصير",
    duration: "24د",
    palette: ["#fca5a5", "#be123c"],
    tags: ["مدرسة", "ذكاء", "حب"]
  },
  {
    id: "toradora",
    title: "Toradora!",
    jp: "とらドラ!",
    tagline: "حب غير متوقع.",
    description: "قصة رومانسية خفيفة مع مواقف طريفة.",
    genres: ["romance", "comedy", "drama"],
    type: "TV",
    status: "Completed",
    era: "2000s",
    score: 8.0,
    episodes: "قصير",
    duration: "24د",
    palette: ["#fdba74", "#f97316"],
    tags: ["مدرسة", "صداقات", "كوميديا"]
  },
  {
    id: "mushoku-tensei",
    title: "Mushoku Tensei",
    jp: "無職転生",
    tagline: "فرصة ثانية في عالم جديد.",
    description: "إيسيكاي غني بالتفاصيل وتطور شخصية واضح.",
    genres: ["isekai", "fantasy", "adventure"],
    type: "TV",
    status: "Ongoing",
    era: "2020s",
    score: 8.3,
    episodes: "متوسط",
    duration: "24د",
    palette: ["#6ee7b7", "#059669"],
    tags: ["عالم آخر", "سحر", "رحلة"]
  },
  {
    id: "re-zero",
    title: "Re:Zero",
    jp: "Re:ゼロから始める異世界生活",
    tagline: "حلقة لا تنتهي من التحديات.",
    description: "كل قرار قد يعيد الزمن إلى البداية من جديد.",
    genres: ["isekai", "thriller", "fantasy"],
    type: "TV",
    status: "Ongoing",
    era: "2010s",
    score: 8.2,
    episodes: "متوسط",
    duration: "25د",
    palette: ["#a5b4fc", "#4f46e5"],
    tags: ["عودة زمن", "توتر", "مصير"]
  },
  {
    id: "promised-neverland",
    title: "The Promised Neverland",
    jp: "約束のネバーランド",
    tagline: "الهروب يحتاج خطة ذكية.",
    description: "أطفال يحاولون النجاة من حقيقة مرعبة.",
    genres: ["horror", "thriller", "mystery"],
    type: "TV",
    status: "Completed",
    era: "2010s",
    score: 8.4,
    episodes: "قصير",
    duration: "23د",
    palette: ["#94a3b8", "#0f172a"],
    tags: ["ذكاء", "هروب", "غموض"]
  },
  {
    id: "made-in-abyss",
    title: "Made in Abyss",
    jp: "メイドインアビス",
    tagline: "عمق مظلم وجمال خطير.",
    description: "رحلة إلى هوة غامضة مليئة بالأسرار.",
    genres: ["adventure", "fantasy", "horror"],
    type: "TV",
    status: "Ongoing",
    era: "2010s",
    score: 8.6,
    episodes: "قصير",
    duration: "24د",
    palette: ["#a7f3d0", "#0f766e"],
    tags: ["مغامرة", "عالم غريب", "تشويق"]
  },
  {
    id: "dr-stone",
    title: "Dr. Stone",
    jp: "Dr.STONE",
    tagline: "العلم يعيد بناء الحضارة.",
    description: "مزيج ممتع من العلم والمغامرة في عالم متجمد.",
    genres: ["sci-fi", "adventure", "comedy"],
    type: "TV",
    status: "Ongoing",
    era: "2010s",
    score: 8.1,
    episodes: "متوسط",
    duration: "24د",
    palette: ["#fde047", "#f97316"],
    tags: ["علم", "بقاء", "اختراع"]
  },
  {
    id: "oshi-no-ko",
    title: "Oshi no Ko",
    jp: "【推しの子】",
    tagline: "عالم النجوم مليء بالأسرار.",
    description: "دراما مشوقة عن الشهرة والهوية.",
    genres: ["drama", "music", "mystery"],
    type: "TV",
    status: "Ongoing",
    era: "2020s",
    score: 8.7,
    episodes: "قصير",
    duration: "24د",
    palette: ["#f9a8d4", "#a855f7"],
    tags: ["نجومية", "دراما", "غموض"]
  },
  {
    id: "frieren",
    title: "Frieren: Beyond Journey's End",
    jp: "葬送のフリーレン",
    tagline: "ما بعد النهاية بداية جديدة.",
    description: "فانتازيا هادئة عن الزمن والذكريات.",
    genres: ["fantasy", "adventure", "drama"],
    type: "TV",
    status: "Ongoing",
    era: "2020s",
    score: 8.9,
    episodes: "قصير",
    duration: "24د",
    palette: ["#a7f3d0", "#38bdf8"],
    tags: ["رحلة", "ذكريات", "سحر"]
  },
  {
    id: "blue-lock",
    title: "Blue Lock",
    jp: "ブルーロック",
    tagline: "الهدف: أقوى مهاجم.",
    description: "منافسة شرسة تجمع أفضل المهاجمين في اليابان.",
    genres: ["sports", "thriller", "drama"],
    type: "TV",
    status: "Ongoing",
    era: "2020s",
    score: 8.2,
    episodes: "متوسط",
    duration: "24د",
    palette: ["#60a5fa", "#1e3a8a"],
    tags: ["كرة قدم", "منافسة", "طموح"]
  },
  {
    id: "chainsaw-man",
    title: "Chainsaw Man",
    jp: "チェンソーマン",
    tagline: "قوة مرعبة بثمن باهظ.",
    description: "أكشن دموي وقصة غير تقليدية.",
    genres: ["action", "horror", "supernatural"],
    type: "TV",
    status: "Ongoing",
    era: "2020s",
    score: 8.4,
    episodes: "قصير",
    duration: "24د",
    palette: ["#f87171", "#7f1d1d"],
    tags: ["رعب", "شيطان", "أكشن"]
  },
  {
    id: "vinland-saga",
    title: "Vinland Saga",
    jp: "ヴィンランド・サガ",
    tagline: "قصة تاريخية عن الانتقام والشرف.",
    description: "ملحمة فايكنج مليئة بالدراما والمعارك.",
    genres: ["action", "historical", "drama"],
    type: "TV",
    status: "Ongoing",
    era: "2010s",
    score: 8.7,
    episodes: "متوسط",
    duration: "24د",
    palette: ["#fcd34d", "#92400e"],
    tags: ["فايكنج", "تاريخ", "حرب"]
  },
  {
    id: "mob-psycho",
    title: "Mob Psycho 100",
    jp: "モブサイコ100",
    tagline: "قوة نفسية بروح خفيفة.",
    description: "أكشن كوميدي مع رسائل قوية عن الذات.",
    genres: ["action", "comedy", "supernatural"],
    type: "TV",
    status: "Completed",
    era: "2010s",
    score: 8.5,
    episodes: "متوسط",
    duration: "24د",
    palette: ["#a5f3fc", "#0284c7"],
    tags: ["قوى نفسية", "ضحك", "نمو"]
  },
  {
    id: "bocchi",
    title: "Bocchi the Rock!",
    jp: "ぼっち・ざ・ろっく！",
    tagline: "موسيقى وصداقة وخجل لطيف.",
    description: "مشاهد ممتعة عن فرقة موسيقية ومرحلة المراهقة.",
    genres: ["music", "slice-of-life", "comedy"],
    type: "TV",
    status: "Completed",
    era: "2020s",
    score: 8.5,
    episodes: "قصير",
    duration: "24د",
    palette: ["#f9a8d4", "#fb7185"],
    tags: ["فرقة", "موسيقى", "يومي"]
  },
  {
    id: "parasyte",
    title: "Parasyte",
    jp: "寄生獣",
    tagline: "غزو صامت داخل الجسد.",
    description: "رعب نفسي وسؤال عميق عن الإنسانية.",
    genres: ["horror", "sci-fi", "drama"],
    type: "TV",
    status: "Completed",
    era: "2010s",
    score: 8.3,
    episodes: "قصير",
    duration: "23د",
    palette: ["#9ca3af", "#14532d"],
    tags: ["كائنات", "بقاء", "توتر"]
  },
  {
    id: "cowboy-bebop",
    title: "Cowboy Bebop",
    jp: "カウボーイビバップ",
    tagline: "مطاردات فضائية بأناقة كلاسيكية.",
    description: "موسيقى جاز وأجواء نوار في رحلة صائدين الجوائز.",
    genres: ["sci-fi", "adventure", "drama"],
    type: "TV",
    status: "Completed",
    era: "classic",
    score: 8.9,
    episodes: "قصير",
    duration: "24د",
    palette: ["#fbbf24", "#1f2937"],
    tags: ["فضاء", "جاز", "كلاسيك"]
  },
  {
    id: "evangelion",
    title: "Neon Genesis Evangelion",
    jp: "新世紀エヴァンゲリオン",
    tagline: "ميكا ودراما نفسية عميقة.",
    description: "قصة معقدة عن المسؤولية والهوية.",
    genres: ["mecha", "drama", "sci-fi"],
    type: "TV",
    status: "Completed",
    era: "classic",
    score: 8.5,
    episodes: "قصير",
    duration: "24د",
    palette: ["#a78bfa", "#1e1b4b"],
    tags: ["ميكا", "نفسية", "كلاسيك"]
  },
  {
    id: "detective-conan",
    title: "Detective Conan",
    jp: "名探偵コナン",
    tagline: "ذكاء محقق في جسد طفل.",
    description: "ألغاز لا تنتهي وتحقيقات ممتعة.",
    genres: ["mystery", "thriller"],
    type: "TV",
    status: "Ongoing",
    era: "classic",
    score: 8.2,
    episodes: "طويل",
    duration: "24د",
    poster: "images.jpeg",
    palette: ["#93c5fd", "#1d4ed8"],
    tags: ["محقق", "ألغاز", "غموض"]
  }
];

const MEDIA_MAP = {
  naruto: { trailerId: "22R0j8UKRzY" },
  "one-piece": { trailerId: "ceQwv3BUbkA" },
  "attack-on-titan": { trailerId: "1XrLuchKZjI" },
  "demon-slayer": { trailerId: "TcuxuwtIhtY" },
  "jujutsu-kaisen": { trailerId: "pkKu9hLT-t8" },
  "my-hero-academia": { trailerId: "tohKs2w4vfA" },
  "death-note": { trailerId: "NlJZ-YgAt-c" },
  "spy-family": { trailerId: "6sosTNRw_uQ" },
  haikyuu: { trailerId: "IZ8iIHpe4Lg" },
  "kaguya-sama": { trailerId: "hjy7vK0hTAE" },
  "mushoku-tensei": { trailerId: "k5VxfJpzy1Q" },
  "dr-stone": { trailerId: "W5VvkyJ7XB0" },
  "made-in-abyss": { trailerId: "kFjP5b5dmYw" },
  "re-zero": { trailerId: "7IQM5EPf2Y0" }
};

const ANIME = ANIME_DATA.map((anime) => {
  const media = MEDIA_MAP[anime.id] || {};
  const poster = anime.poster || (media.trailerId ? getTrailerThumb(media.trailerId) : undefined);
  return { ...anime, ...media, poster };
});

const byId = new Map(ANIME.map((anime) => [anime.id, anime]));

const STORAGE_KEY = "animeGoldWatchlist";

const escapeHtml = (value) =>
  String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
